### ISSUE TITLE
Hackage version 0.2.1 uses old `FieldLens` class

### ISSUE THREAD

**Issue by rabipelais** [nikita-volkov/record#13]
I don't know if this is intentional, but the [hackage version of the package](http://hackage.haskell.org/package/record-0.2.1/docs/Record-Types.html) for release 0.2.1 uses the `FieldLens` class, while the 0.2.1 version in this repository uses renamed this to just `Field`.

**Comment by nikita-volkov** [comment]
The "master" branch is a few commits ahead of the latest release and contains some updates, which are intended for the next major release. In [the Tags section](https://github.com/nikita-volkov/record/tags) you can navigate to any commit accommodating a specific release.
