### ISSUE TITLE
Larger records do not work

### ISSUE THREAD

**Issue by PaulVisschers** [nikita-volkov/record#17]
In version 0.3.0, when I make records that are up to 12 fields everything works fine, but if I add a 13th I get the following error:

```
Main.hs:5:13:
    `Record.Types.Record12' is applied to too many type arguments
    In the type `Record.Types.Record12 "n1" Int "n10" Int "n11" Int "n12" Int "n
13" Int "n2" Int "n3" Int "n4" Int "n5" Int "n6" Int "n7" Int "n8" Int "n9" Int'

    In the type declaration for `Test'
```

If I add a 14th one, the error is similar, but it uses the constructor `Record13`. There seems to be an 'off-by-one' error somewhere.

Minimal example:

```
{-# LANGUAGE QuasiQuotes #-}

import Record

type Test = [r| {
  n1 :: Int,
  n2 :: Int,
  n3 :: Int,
  n4 :: Int,
  n5 :: Int,
  n6 :: Int,
  n7 :: Int,
  n8 :: Int,
  n9 :: Int,
  n10 :: Int,
  n11 :: Int,
  n12 :: Int,
  n13 :: Int
  } |]
```

**Comment by nikita-volkov** [comment]
A [very silly bug](https://github.com/nikita-volkov/record/commit/a8fb35654eae36eb8dda806cf865de6be975511e). ) Thank you. Fixed in 0.3.1
