### ISSUE TITLE
splicing integer literals does not work correctly

### ISSUE THREAD

**Issue by soenkehahn** [nikita-volkov/record#2]
When adding a type signature to the demo file as in this commit: https://github.com/soenkehahn/record/commit/04746b5836aacc59240017523db3cde88df387c2, compilation of that demo module fails with `No instance for (Fractional Int) arising from the literal ‘18.0’ [snip]`.

I guess without that signature it just defaulted to a record with `{day :: Double}`.

**Comment by nikita-volkov** [comment]
Reproduced. Getting on it. Thanks

**Comment by nikita-volkov** [comment]
Fixed in 0.1.2

**Comment by soenkehahn** [comment]
Thanks!
