### ISSUE TITLE
record-0.4.0.0 crashes Haddock

### ISSUE THREAD

**Issue by peti** [nikita-volkov/record#22]
Citing from http://hydra.cryp.to/build/926412/nixlog/2/raw:

```
haddock: internal error: spliceURL UnhelpfulSpan
```

This is Haddock version 2.16.0 as shipped with GHC 7.10.1.

**Comment by nikita-volkov** [comment]
I'm not sure what that could be. Seems more like a bug of Haddock.

**Comment by nikita-volkov** [comment]
The 0.4.0.1 release fixes one issue for GHCs below 7.10. It might fix this one as well.

**Comment by nikita-volkov** [comment]
Turns out, it is in fact a bug of Haddock. See https://github.com/feuerbach/standalone-haddock/issues/8.

**Comment by peti** [comment]
The new version fails, too, unfortunately: http://hydra.cryp.to/build/926867/nixlog/1/raw. Not sure what one can do about this.

**Comment by nikita-volkov** [comment]
The 0.4.0.2 version should contain a work-around for this bug.

**Comment by peti** [comment]
Yes, the new version works fine. Thank you!

**Comment by nikita-volkov** [comment]
Good. Thanks.
