### ISSUE TITLE
Support GHC 8: drop ImpredicativeTypes?

### ISSUE THREAD

**Issue by cumber** [nikita-volkov/record#29]
After a bit of experimentation, it looks like the only thing stopping this building on GHC8 is the ImpredicativeTypes extension. I removed that, bumped the base constraint, and it builds fine.

As far as I can tell there isn't any reason to have it turned on here. I have no idea why it's causing the compilation errors in GHC 8, but the migration guide does state:

> Note that the -XImpredicativeTypes extension, which has been known to be broken for many years, is even more broken than usual in this release (see #11319, #11675, and others). During pre-release testing we encountered a number of projects that broke with confusing type errors due to (often unnecessary) use of -XImpredicativeTypes. Users of -XImpredicativeTypes do so at their own risk!

So it seems to be expected that ImpredicativeTypes can cause type errors even in modules that aren't actually using the feature.

Should it just be dropped? If it's not intended to be used, it doesn't seem to be a safe extensions to just have on by default (since it's broken, changes in its level of broken-ness between GHC releases, and affects code that doesn't need it).

**Comment by nikita-volkov** [comment]
You're absolutely right. I've been dropping it from all of my projects gradually. Just hadn't reached "record" yet. The fixed version is released now.

BTW. If you're looking for the Template-Haskell-based version, please check out the 0.3.\* version of the library.

**Comment by cumber** [comment]
Is the 0.4 version intended as an improvement on 0.3, or just a different technology for exposing the new syntax? I was a bit surprised to not find the quasi quotes from your blog post, yes. Should I just be using 0.3?) Latest LTS / nix releases only have 0.4)

**Comment by nikita-volkov** [comment]
It's the same technology and in a few senses 0.4 is an improvement over 0.3.

The version 0.4 of the library now only exports the types with an intent for other packages to implement the syntax either using TH or other methods. Right now only the preprocessor is implemented but later the TH version might appear as well. Either way, right now the combination of "record" and "record-preprocessor" is the recommended way of using the library. Please see the description pages of the packages (and the referred demos) for instructions.
